spring:
  application:
    name: microservice-disney

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:disney
    username: admin
    password: admin
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: h2
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

springdoc:
  swagger-ui:
    path: /openapi/ui
    enabled: true
    operations-sorter: method
  api-docs:
    path: /openapi/docs
    enabled: true

logging:
  level:
    sql: debug
